# Generated by Django 5.0 on 2023-12-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='/media/default-user.png', upload_to='profile_picture/'),
        ),
    ]
