# Generated by Django 5.0 on 2024-01-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_wishlist_app', '0005_user_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_address',
        ),
    ]
