# Generated by Django 5.0 on 2024-01-01 07:05

import category_product_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_profile_picture'),
        ('category_product_app', '0002_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('desc', models.TextField(blank=True, default='')),
                ('main_image', models.ImageField(default='default.jpg', upload_to=category_product_app.models.productImage_path)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_product_app.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_product_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('size', models.ManyToManyField(to='category_product_app.size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subimage', models.ImageField(default='default.jpg', upload_to=category_product_app.models.subImage_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_product_app.product')),
            ],
        ),
    ]
