# Generated by Django 4.2.7 on 2023-12-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_credentials_app', '0003_user_user_type_alter_user_address_alter_user_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=30),
        ),
    ]
