# Generated by Django 4.2.7 on 2023-12-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_credentials_app', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')])),
                ('product_brand', models.CharField(choices=[('Allen Solly', 'Allen Solly'), ('US Polo', 'US Polo'), ('Supreme', 'Supreme'), ("Levi's", "Levi's"), ('Zara', 'Zara'), ('Diesel', 'Diesel'), ('Calvin Klein', 'Calvin Klein'), ('Tommy Hilfiger', 'Tommy Hilfiger')])),
                ('product_size', models.CharField(choices=[('XS', ' '), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')])),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_desc', models.TextField(default='')),
                ('product_slug', models.SlugField(default='', max_length=20)),
                ('product_image', models.ImageField(default='', upload_to='product_picture/')),
                ('product_price', models.FloatField(default='100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_credentials_app.user')),
            ],
        ),
    ]
