# Generated by Django 5.0 on 2024-01-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_address',
        ),
    ]
